pub const OPTIFINE_PREAMBLE: &str = r#"#define MC_VERSION 11800
#define MC_GL_VERSION 320
#define MC_GLSL_VERSION 150
#define MC_OS_LINUX
#define MC_GL_VENDOR_NVIDIA
#define MC_GL_RENDERER_GEFORCE
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_OLD_HAND_LIGHT
#define MC_OLD_LIGHTING"#;